import type { PlanItem } from "@/lib/content";
import { hasPrice, priceLabel, priceUnit } from "@/lib/content";

/* The single price component used by the hero anchor and every plan card.
   The visual row is aria-hidden and the accessible string is generated by
   priceLabel() from the same plan object, so the two can never diverge.

   A plan without a price prints no lockup at all — the caller renders a
   "Call for pricing" button instead. Never render an invented figure. */

export function PriceLockup({
  plan,
  size = "md",
}: {
  plan: PlanItem;
  size?: "md" | "lg";
}) {
  if (!hasPrice(plan)) {
    return (
      <div className={`lockup lockup--${size} lockup--ask`}>
        <p className="lockup__ask">Call for pricing</p>
        {plan.promoQualifier ? <p className="lockup__qual">{plan.promoQualifier}</p> : null}
      </div>
    );
  }

  return (
    <div className={`lockup lockup--${size}`}>
      <p className="lockup__row" aria-hidden="true">
        <span className="lockup__cur">$</span>
        <span className="lockup__int">{plan.price}</span>
        {plan.cents ? <span className="lockup__cents">.{plan.cents}</span> : null}
        <span className="lockup__per">{priceUnit(plan)}</span>
      </p>
      <p className="sr-only">{priceLabel(plan)}</p>
      {plan.promoQualifier ? <p className="lockup__qual">{plan.promoQualifier}</p> : null}
      {plan.stepUp ? <p className="lockup__step">{plan.stepUp}</p> : null}
      <p className="lockup__step">Plus taxes, fees and surcharges.</p>
    </div>
  );
}
